name: "CI/CI Pipeline for LMS Front-End"
on: 
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3

      - name: Installing Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Installing SASS
        run: npm i -g sass

      - name: 'Compiling *.sass files to *.css'
        run: sass scss:css

      - name: Zipping to deploy
        run: zip -r dist.zip css pages js index.html

      - name: Testing
        run: ls -la
      
